import type { Metadata } from "next";
import { montserrat, inter, robotomono, mulish, lato, roboto } from "./font";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${inter.variable} ${robotomono.variable} ${mulish.variable} ${lato.variable} ${roboto.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
